[package]
name = "breeze"
version = "0.1.3"
edition = "2021"

[dependencies]
axum = { version = "0.6.1", features = ["macros"] }
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7.4", features = ["full"] }
tokio-stream = "0.1"
tower = "0.4.13"
bytes = "1"
rand = "0.8.5"
async-recursion = "1.0.0"
walkdir = "2"
log = "0.4"
pretty_env_logger = "0.5.0"
archived = { path = "./archived" }
